spring:
  application:
    name: color-service
  datasource:
    url: jdbc:postgresql://localhost:5432/colorsdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  bootstrap-servers: localhost:9092

server:
  port: 8081
