server:
  port: 8083

spring:
  application:
    name: color-analysis-consumer

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: color-analysis-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.mutlukodcu.shared.kafka"
        spring.json.value.default.type: com.mutlukodcu.shared.kafka.PhotoEvent
      auto-offset-reset: earliest

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      missing-topics-fatal: false

logging:
  level:
    root: INFO
    com.mutlukodcu: DEBUG
