server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mutlukodcu
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    org.hibernate.SQL: DEBUG